// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ezwebsocket.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ezwebsocket.WebsocketManager;

/**
 * Use this if you need custom timeout settings + Configure a microflow to be executed when a client disconnects
 * 
 * >Example usecase: you want a user to be displayed as "offline" after they close the browser
 * 
 * - Session timeout can be set to 0 for infinite* sessions
 * *NOTE: Mendix cloud will still disconnect after 60 seconds of inactivity
 * 
 * Set pingTime and pongTime if you want to control the keepalive mechanism
 * - The server will ping the client every <pingTime> seconds
 * - The server will disconnect the client after not receiving a response after <pongTime> seconds
 * > Setting pingTime to 0 (or negative) will turn off the keepalive mechanism and clients will timeout after <sessionTimeout> seconds
 * 
 * > Configure the microflow to be called on disconnect (must have a string parameter)
 * > Configure the name of this string parameter
 * > Pass the parameter using the Websocket Close Behaviour tab on the client widget
 * 
 */
public class JA_AddWebsocketEndpoint_Advanced_CallMicroflowOnDisconnect extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String websocketIdentifier;
	private final java.lang.Long sessionTimeout;
	private final java.lang.Long pingTime;
	private final java.lang.Long pongTime;
	private final java.lang.String onCloseMicroflow;
	private final java.lang.String onCloseMicroflowParameterKey;

	public JA_AddWebsocketEndpoint_Advanced_CallMicroflowOnDisconnect(
		IContext context,
		java.lang.String _websocketIdentifier,
		java.lang.Long _sessionTimeout,
		java.lang.Long _pingTime,
		java.lang.Long _pongTime,
		java.lang.String _onCloseMicroflow,
		java.lang.String _onCloseMicroflowParameterKey
	)
	{
		super(context);
		this.websocketIdentifier = _websocketIdentifier;
		this.sessionTimeout = _sessionTimeout;
		this.pingTime = _pingTime;
		this.pongTime = _pongTime;
		this.onCloseMicroflow = _onCloseMicroflow;
		this.onCloseMicroflowParameterKey = _onCloseMicroflowParameterKey;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return WebsocketManager.addWebsocketEndpointWithOnCloseMicroflow(websocketIdentifier, sessionTimeout, pingTime,
				pongTime != null ? pongTime : 0, onCloseMicroflow,
				onCloseMicroflowParameterKey);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_AddWebsocketEndpoint_Advanced_CallMicroflowOnDisconnect";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
