// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package ezwebsocket.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import ezwebsocket.WebsocketManager;

/**
 * Notify all subscribers to the context object/objectId
 * Either an action or message (or both) should be configured
 * - Action will be executed according to configuration in the client widget
 * - Message will be passed to the configured message attribute
 * - In case both are configured, the message will be set before the action is executed
 */
public class JA_Notify extends CustomJavaAction<java.lang.Boolean>
{
	private final java.lang.String websocketIdentifier;
	private final java.lang.String objectId;
	private final java.lang.String action;
	private final java.lang.String message;

	public JA_Notify(
		IContext context,
		java.lang.String _websocketIdentifier,
		java.lang.String _objectId,
		java.lang.String _action,
		java.lang.String _message
	)
	{
		super(context);
		this.websocketIdentifier = _websocketIdentifier;
		this.objectId = _objectId;
		this.action = _action;
		this.message = _message;
	}

	@java.lang.Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		return WebsocketManager.notify(objectId, action, message, websocketIdentifier);
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_Notify";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
