// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import { Big } from "big.js";
import "mx-global";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @param {string} parameter
 * @returns {Promise.<void>}
 */
export async function Demo(parameter) {
	// BEGIN USER CODE

    // Create the toast container if it doesn't exist
    if (!document.getElementById("custom-toast-container")) {
        var toastContainer = document.createElement("div");
        toastContainer.id = "custom-toast-container";
        document.body.appendChild(toastContainer);

        // Style the toast container (CSS can also be external or more detailed)
        var containerStyles = `
            #custom-toast-container {
                position: fixed;
                bottom: 20px;
                right: 20px;
                z-index: 9999;
                display: flex;
                flex-direction: column;
                gap: 10px;
            }
            .custom-toast {
                background-color: rgba(0, 0, 0, 0.8);
                color: #fff;
                padding: 10px 20px;
                border-radius: 5px;
                font-size: 14px;
                min-width: 200px;
                text-align: center;
                opacity: 0;
                transition: opacity 0.5s ease-in-out;
            }
            .custom-toast.show {
                opacity: 1;
            }
        `;
        var styleSheet = document.createElement("style");
        styleSheet.type = "text/css";
        styleSheet.innerText = containerStyles;
        document.head.appendChild(styleSheet);
    }

    // Create the toast element
    var toast = document.createElement("div");
    toast.classList.add("custom-toast");
    toast.innerText = message;

    // Append the toast to the container
    document.getElementById("custom-toast-container").appendChild(toast);

    // Show the toast
    setTimeout(function () {
        toast.classList.add("show");
    }, 100); // Slight delay for the transition

    // Remove the toast after 3 seconds
    setTimeout(function () {
        toast.classList.remove("show");
        setTimeout(function () {
            toast.remove();
        }, 500); // Wait for the fade-out transition before removing the element
    }, 3000);

	// END USER CODE
}